### ISSUE TITLE
Saving configuration

### ISSUE THREAD

**Issue by ghuname** [vsajip/py-cfg-lib#1]
Hi,

is it possible to save configuration?
For example, let's say that when my application starts, I would like to create configuration for the first time (defaults) and save it. From now on, I would like to read configuration and save, let's say some last values.

Can I do it with config library?

Regards

**Comment by vsajip** [comment]
No, it doesn't support writing configurations - different people have different requirements for how they want to format their configuration, for example. This library reads configurations from JSON so you could save your configuration in JSON format.

**Comment by ghuname** [comment]
Thanks, do you maybe have a suggestion for a module that is able to read/save python data types (strings, dates, array, dicts...)?

**Comment by vsajip** [comment]
I already mentioned JSON - it is handled using the `json` module, which is part of Python.
