### ISSUE TITLE
Nested includes loose rootpath and include_path

### ISSUE THREAD

**Issue by emsems** [vsajip/py-cfg-lib#2]
Hi,

thank you for this great package, and that you picked up the development again. I enjoy its power and flexibility a lot.

I have a configuration with nested includes, i.e. main config file includes a second one which again includes a third one (all relative paths).
This raises an Exception because the Config object resulting from the second file doesn't have self.rootpath set.
I use the latest version (0.5.0.post0)

I think this could be fixed with this code snipplet (\_\_init__.py, line 361):

        with open_file(p) as f:
            rootdir = os.path.dirname(p)
            p = Parser(f)
            result = p.container()
            if isinstance(result, MappingBody):
                cfg = Config(
                    None, context=config.context, cache=self.config._cache is not None,
                    include_path=config.include_path, rootdir=rootdir
                )
                cfg._parent = config
                cfg._data = cfg._wrap_mapping(result)
                result = cfg

What do you think?

**Comment by vsajip** [comment]
> I enjoy its power and flexibility a lot.

Thanks for the feedback! I'll have time to look at this early next week.

**Comment by vsajip** [comment]
I've made the fix internally, working on a test now.

**Comment by emsems** [comment]
Great, thank you so much!
